# Generated by Django 4.0.5 on 2022-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(max_length=1000, upload_to='news_images')),
                ('description', models.TextField()),
                ('publishing_site', models.TextField()),
                ('publishing_date', models.DateTimeField()),
                ('link', models.URLField(max_length=256)),
                ('guid', models.TextField()),
            ],
            options={
                'ordering': ['-publishing_date', 'title'],
                'get_latest_by': 'publishing_date',
            },
        ),
    ]
