# Generated by Django 4.0.5 on 2022-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='short_description',
            field=models.TextField(default=None),
        ),
    ]
